version: '3'
services:
  mariadb:
    image: mariadb:latest
    container_name: pizzaservice-mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=rootpassword
      - MARIADB_DATABASE=pizzaapp
      - MARIADB_USER=pizzauser
      - MARIADB_PASSWORD=pizzapassword
    ports:
      - "3307:3306"
    volumes:
      - mariadb-data:/var/lib/mysql

volumes:
  mariadb-data: